In [4]:
import numpy as np  # Import NumPy for array and matrix operations


# Function to create elimination matrix for one step
def elimination_matrix(A: np.ndarray, step: int):
    # Get number of rows/columns of A
    n = A.shape[0]

    # Start with identity matrices
    elim_mtx = np.eye(n)       # Used to remove (eliminate) numbers below the pivot
    elim_mtx_inv = np.eye(n)   # Used later to form the L matrix

    # Only do this if step is valid
    if 0 < step < n:
        # Find how much to multiply the pivot row by to eliminate lower rows
        a = A[:, step - 1] / A[step - 1, step - 1]

        # Add negative values to elim_mtx → this will zero out below the pivot
        elim_mtx[step:, step - 1] = -a[step:]

        # Add positive values to elim_mtx_inv → used to build L
        elim_mtx_inv[step:, step - 1] = a[step:]

    # Return both matrices
    return elim_mtx, elim_mtx_inv

In [5]:
# Function to perform LU decomposition
def LU(A: np.ndarray):
    # Get size of matrix A
    n = A.shape[0]

    # Start L as identity matrix (will store multipliers)
    L = np.eye(n)

    # Copy A into U (we’ll make it upper triangular)
    U = np.copy(A)

    # Repeat elimination for each column
    for step in range(1, n):
        # Get elimination matrix for this step
        elim_mtx, elim_mtx_inv = elimination_matrix(U, step=step)

        # Apply elimination → makes zeros below the pivot
        U = np.matmul(elim_mtx, U)

        # Update L → stores the multipliers (inverse of elimination)
        L = np.matmul(L, elim_mtx_inv)

    # Return L (lower) and U (upper) matrices
    return L, U


In [6]:
# ---- Testing the code ----
if __name__ == "__main__":
    np.random.seed(0)  # To get the same random numbers every time

    # Create a random 4x4 matrix with values between -5 and +5
    A = 10 * np.random.rand(4, 4) - 5

    print("Matrix A:\n", A)

    # Perform LU decomposition
    L, U = LU(A)

    print("\nLower triangular matrix L:\n", L)
    print("\nUpper triangular matrix U:\n", U)

    # Check if L * U = A (approximately)
    print("\nReconstructed A from L and U:\n", np.matmul(L, U))
    print("\nIs L * U close to A?:", np.allclose(np.matmul(L, U), A))


Matrix A:
 [[ 0.48813504  2.15189366  1.02763376  0.44883183]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [ 0.68044561  4.25596638 -4.28963942 -4.128707  ]]

Lower triangular matrix L:
 [[ 1.          0.          0.          0.        ]
 [-1.56401804  1.          0.          0.        ]
 [ 9.49865761 -4.4782878   1.          0.        ]
 [ 1.39397002  0.26039596  2.44880593  1.        ]]

Upper triangular matrix U:
 [[ 4.88135039e-01  2.15189366e+00  1.02763376e+00  4.48831830e-01]
 [ 0.00000000e+00  4.82454164e+00  9.83109851e-01  4.61971109e+00]
 [ 0.00000000e+00  3.55271368e-15 -2.44124201e+00  1.67140451e+01]
 [ 0.00000000e+00 -8.69990631e-15 -8.88178420e-16 -4.68867719e+01]]

Reconstructed A from L and U:
 [[ 0.48813504  2.15189366  1.02763376  0.44883183]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [ 0.68044561  4.25596638 -4.28963942 -4.128707  ]]

Is L * U close