In [1]:
import numpy as np

In [3]:
X = np.array([1.5,3,67,89,-4.5])
X

array([ 1.5,  3. , 67. , 89. , -4.5])

In [8]:
np.ones(shape=3)

array([1., 1., 1.])

In [9]:
np.zeros(shape=6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.random.rand(20)

array([0.49278395, 0.70433416, 0.37074044, 0.00693574, 0.67756466,
       0.03690062, 0.43512357, 0.76256642, 0.09498618, 0.38699502,
       0.46919118, 0.93271726, 0.69850938, 0.28899048, 0.50414703,
       0.44497112, 0.15172742, 0.04231098, 0.64672507, 0.0515397 ])

In [11]:
X[1:3]

array([ 3., 67.])

In [12]:
X[3] = 100

In [16]:
X

array([  1.5,   3. ,  67. , 100. ,  -4.5])

In [17]:
X.dtype

dtype('float64')

In [18]:
for i in X:
    print(i)

1.5
3.0
67.0
100.0
-4.5


In [20]:
v1 = np.array([1,-4,5,6])
v2 =  np.array([-3,5,9,-5])

In [21]:
v1+v2

array([-2,  1, 14,  1])

In [22]:
10*v1

array([ 10, -40,  50,  60])

In [23]:
v1*v2

array([ -3, -20,  45, -30])